version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "my_database"
    ports:
      - "3306:3306"
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8888:1234"
    environment:
      DB_DRIVER: "mysql+pymysql"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "my_database"
